### ISSUE TITLE
does it support keyed object ?

### ISSUE THREAD

**Issue by sumpan** [DanielYWoo/fast-object-pool#15]
for example ,I have 100 jmx servers to connect ,so i hava to identify them with ip and port or id 
can ’FOP‘ helps me to maintain this connections ?

**Comment by DanielYWoo** [comment]
In short, no.

Let's say you have 3 servers s1, s2 and s3, each maintain 2 connections, you want to put all of the 6 connections into a single pool and get it by something like getConnection(servierId)? 

If that's your case, you probably need a HashMap of connection pools, key is your server id, value is a tiny connection pool to your server with the id. You need to wrap a thin layer on top of FOP. Actually if you try other object pools, most likely, the same way.

**Comment by DanielYWoo** [comment]
close since no more response
