### ISSUE TITLE
Risk condition causing thread blocked

### ISSUE THREAD

**Issue by CookieDSEU** [DanielYWoo/fast-object-pool#25]
```
Poolable<T> freeObject = subPool.getObjectQueue().poll();
if (freeObject == null) {
    // increase objects and return one, it will return null if reach max size
    subPool.increaseObjects(1);
    try {
        if (blocking) {
            freeObject = subPool.getObjectQueue().take();
        } else {
            freeObject = subPool.getObjectQueue().poll(config.getMaxWaitMilliseconds(), TimeUnit.MILLISECONDS);
            if (freeObject == null) {
                throw new RuntimeException("Cannot get a free object from the pool");
            }
        }
    } catch (InterruptedException e) {
        throw new RuntimeException(e); // will never happen
    }
}
```

Code in `borrowObject()` may cause the thread blocked if the increased object was immediately taken by another thread.

Although I knew I can use `borrowObject(false)` to solve the issue. But I still regard this as a multi-thread bug. The newly created object is ought to be consumed by its own thread.

**Comment by DanielYWoo** [comment]
thanks, and good catch.
Actually even borrowObject(false) also suffers the performance. If T1 increases the pool, then T2 takes the new object, T1 will wait MaxWaitMilliseconds which is unnecessary.
I changed the code to poll and increase in a loop, if T2 takes away the new object in queue, T1 will find it in the next poll loop and increase it again, until the pool is full.
```
    private Poolable<T> getObject(boolean noTimeout) {
        if (shuttingDown) {
            throw new IllegalStateException("Your pool is shutting down");
        }
        int partition = (int) (Thread.currentThread().getId() % this.config.getPartitionSize());
        ObjectPoolPartition<T> subPool = this.partitions[partition];
        Poolable<T> freeObject;
        do { // loop to ensure: if T1 increases an object but T2 takes it, then T1 can poll and increase it again
            freeObject = subPool.getObjectQueue().poll();
            if (freeObject == null && subPool.increaseObjects(1) <= 0) { // full, have to wait
                try {
                    if (noTimeout) {
                        freeObject = subPool.getObjectQueue().take();
                    } else {
                        freeObject = subPool.getObjectQueue().poll(config.getMaxWaitMilliseconds(), TimeUnit.MILLISECONDS);
                        if (freeObject == null) {
                            throw new RuntimeException("Cannot get a free object from the pool");
                        }
                    }
                } catch (InterruptedException e) {
                    throw new RuntimeException(e); // will never happen
                }
            }
        } while (freeObject == null);
        freeObject.setLastAccessTs(System.currentTimeMillis());
        return freeObject;
    }

```

**Comment by DanielYWoo** [comment]
Let me know if this is fine to you, I will probably release a new version in the next few days.

**Comment by CookieDSEU** [comment]
I'm not sure but isn't it 
`freeObject = subPool.getObjectQueue().take();`
->
`freeObject = subPool.getObjectQueue().poll();`
at line 12 in your code block?

**Comment by DanielYWoo** [comment]
@CookieDSEU It should be "take", at line 12(actually 13).  The code is simplified as this:
```
1       do {
2           freeObject = poll();
3           if (freeObject is empty && increase fails due to full) {
4                wait for free object
5            }
6        } while (freeObject == null);
```
If there is no free objects, T1 gets null at line 2, it tries to increase the pool, then two scenarios.
1) If the pool is full, T1 has to wait, that's why we use "take without timeout" and "poll with timeout", depending on the noTimeout parameter.
2) if the pool is not full, 
2.1) If T2 takes the new increased object by T1 at line 3, T1 will loop again and poll again and realize the new object is taken by other threads after line 2, so T1 will try to increase it again. We could see multiple hot spin loops here, until it gets one, or the pool is full.
2.2) if T2 does not take the new increased object, T1 will get it by poll() at line 2 in the next loop.

**Comment by CookieDSEU** [comment]
Oh, yeah. That's correct. I missed that it is `&&` rather than `||` at line 3.
Then it makes sense.
