### ISSUE TITLE
Endless loop with partition shutdown

### ISSUE THREAD

**Issue by ncoe** [DanielYWoo/fast-object-pool#32]
https://github.com/DanielYWoo/fast-object-pool/blob/62baf75400f49c91bab0f19ca1660a85382df64b/src/main/java/cn/danielw/fop/ObjectPoolPartition.java#L95

If for any reason an object is leaked, the shutdown method will not terminate. Would it be possible to have a force shutdown method, or shutdown with a timeout option?

**Comment by DanielYWoo** [comment]
I can add a timeout parameter for each partition.  Please review #33

**Comment by DanielYWoo** [comment]
thanks for the finding, please re-open it if you still have this problem.
will release in the next couple of days.
