### ISSUE TITLE
More flexible scavenger model

### ISSUE THREAD

**Issue by shabino** [DanielYWoo/fast-object-pool#60]
The current scavenger scheme is thread-per-pool. I have a use case where I could have 100+ pools (caching byte[] of various lengths for image processing), and I'd prefer not to have 100 scavenger threads running.

Would an option of providing an ObjectPool with a ScheduledExecutorService upon construction work? The pool then would schedule its own scavenging and cancel the scheduled job upon shutdown. I'd be willing to submit a PR with this change (or another scheme you propose) if you're open to it.

**Comment by DanielYWoo** [comment]
Sounds cool! 

Maybe, the easy way to do this is to provide a method `setScavenger(YourImplementation)`, and your implementation can access all the internal partitions and implement whatever scavenge logic there. 

But there will be some challenges to implement a cross-pool scavenger with multi-threading.
- How do we submit tasks to the executor to scavenge? Currently, with a single scavenger it respects the `scavengeIntervalMilliseconds` and pause peoridically. Now we have multiple threads, how do we tune the frequency of it? e.g., we can periodically submit a single partition to the executor with `scavengeIntervalMilliseconds`, or we submit all partitions in batch with `scavengeIntervalMilliseconds`. The second option could cause some spikes, the first option could keep the executor hungry.
- we may have big pools and small pools. With multiple scavengers we need to ensure they handle the workload evenly but without too much data race. We better don't use the JDK's default executor.
- we still need to keep the code lean so everybody can read and understand it.

What's your plan to implement it?

**Comment by DanielYWoo** [comment]
Hi @shabino do you still want something like that?

**Comment by shabino** [comment]
I don't work for the org that needed this anymore, so no. No idea if they're even still using object pooling. Thanks for the follow-up though!

**Comment by DanielYWoo** [comment]
Let me close this ticket for now, Thanks.
